### PR TITLE
replace Arbitrary instance with Gen

### PR DESCRIPTION
**Pull request by matthewleon**
moves `purescript-quickcheck` to dev dependencies

addresses https://github.com/hdgarrood/purescript-modular-arithmetic/issues/2

### CODE REVIEW

**Comment by hdgarrood** [comment]
This is unfortunately not as nice as I hoped it would be - I guess because we're missing https://github.com/purescript/purescript-quickcheck/issues/47 ?

**Comment by matthewleon** [comment]
Yes, something like that would be really helpful.

**Comment by matthewleon** [comment]
Actually, I think all we really need is this: https://github.com/garyb/purescript-quickcheck-laws/issues/35

**Comment by hdgarrood** [comment]
Looks great! I'm happy to merge once the prerequisite changes in quickcheck-laws have been merged and tagged.

**Comment by hdgarrood** [comment]
Thanks for this PR, but I realised there's a simpler way of achieving this; see https://github.com/hdgarrood/purescript-modular-arithmetic/commit/1410464d10f7a08fe9a554b6e7c2f171642fce1e

**Pull request closed without merging**
